### ISSUE TITLE
Suboptimal formatting of reference "Dingledine2004"

### ISSUE THREAD

**Issue by auerswal** [wkumari/draft-wkumari-dnsop-alt-tld#9] opened 2021-07-11 17:47 UTC
The *Dingledine2004* reference is formatted in a suboptimal way in all three display renderings (text, PDF, and "htmlized") on the datatracker:

1. There is a comma. followed by two space characters, followed by another comma, instead of just one comma.
2. The URL is enclosed in two sets of less than / greater than characters, instead of just one.

Issue one may be a missing feature in the renderer, i.e., an empty field is not omitted.

Issue two may be caused by having added `&lt;` and `&gt;` to the `target` attribute.

I do not have the IETF XML tooling installed, and thus cannot test possible fixes.  Therefore just this GitHub issue.

**Comment by wkumari** [comment] 2021-07-13 18:24
Ah, thanks. I'm not quite sure how the XML got munged to add the &lt; and &gt;, but I've fixed it.
The extra spaces was caused by an unneeded:
`<seriesInfo name="" value=""/>` tag, which I've removed. 

Draft submission cutoff occurred yesterday, so I'll have to wait till it reopens to post a new version, but fixed in GH for now.

**Closed** 2021-07-13 18:33 UTC
